<?php
/**
 * Created by PhpStorm.
 * User: claudio
 * Date: 23/07/15
 * Time: 0.59
 */

namespace it\thecsea\twofactorDir;

/**
 * Class twofactorDir
 * @author Claudio Cardinale <cardi@thecsea.it>
 * @copyright 2015 Claudio Cardinale
 * @version 1.0.0
 * @package it\thecsea\twofactorDir
 */
class twofactorDir
{
    /**
     * @var string
     */
    private $dir;
    /**
     * @var twofactorAdapter
     */
    private $twofactorAdapter;
    /**
     * @var string
     */
    private $secret;

    public function __construct($dir = ".", $serviceName = "none")
    {
        $this->dir = $dir;
        $this->twofactorAdapter = new twofactorAdapter();
        $this->twofactorAdapter->setDir($this->dir);
        $this->twofactorAdapter->setServiceName($serviceName);
        $secret = $this->readSecret();
        if($secret) {
            //I have a secret stored, so I set it as secret
            $this->twofactorAdapter->setSecret($secret);
        }else
        {
            //I don't have a secret stored so I store the secret generated by library
            $this->storeSecret($this->twofactorAdapter->getSecret());
        }
        $this->secret = $this->twofactorAdapter->getSecret();
    }

    /**
     * The __toString method allows a class to decide how it will react when it is converted to a string.
     *
     * @return string
     * @link http://php.net/manual/en/language.oop5.magic.php#language.oop5.magic.tostring
     */
    function __toString()
    {
        // TODO: Implement __toString() method.
    }

    /**
     * When an object is cloned, PHP 5 will perform a shallow copy of all of the object's properties.
     * Any properties that are references to other variables, will remain references.
     * Once the cloning is complete, if a __clone() method is defined,
     * then the newly created object's __clone() method will be called, to allow any necessary properties that need to be changed.
     * NOT CALLABLE DIRECTLY.
     *
     * @return mixed
     * @link http://php.net/manual/en/language.oop5.cloning.php
     */
    function __clone()
    {
        // TODO: Implement __clone() method.
    }


    /**
     *
     */
    static private function redirect301()
    {
        header("HTTP/1.1 301 Moved Permanently");
        header("Location: ".(isset($_SERVER["REQUEST_SCHEME"]) && $_SERVER["REQUEST_SCHEME"] == "https"?"https":"http").$_SERVER["HTTP_HOST"]."/".$_SERVER["REQUEST_URI"]);
    }

    /**
     * CAUTION this method uses session_start, it must be called before any print
     * @return bool true if the redirect is done
     */
    public function redirectCheck()
    {
        session_start();
        if(isset($_SESSION['logged']))
        {
            self::redirect301();
            return true;
        }else
        {
            return false;
        }
    }

    /**
     * CAUTION this method uses session_start, it must be called before any print
     * this method checks code and performs login
     * @param string $code
     * @return bool true if the code is corret
     */
    public function checkCode($code)
    {
        $res = $this->twofactorAdapter->check($code);
        session_start();
        $_SESSION['logged'] = "";
        return $res;
    }

    private function storeSecret($secret)
    {
        $str = "<?php\nreturn $secret;";
        file_put_contents($this->dir."/secret.php",$str);
    }

    private function readSecret()
    {
        $name = $this->dir."/secret.php";
        return (require ($name));
    }


    /**
     * Install library into a dir
     * @param string $dir
     */
    static public function install($dir = ".")
    {
        $f = fopen($dir . "/.htaccess", "a");
        fwrite($f, file_get_contents(__DIR__ . "/../files/.htaccess"));
        fclose($f);

        $f = fopen($dir . "/redirect.php", "w");
        fwrite($f, file_get_contents(__DIR__ . "/../files/redirect.php"));
        fclose($f);
    }
}